version: "3.8"
services:
  deep_learning:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=hi
      #GRANT_SUDO: "yes"
    # enable sudo permissions
    user: "root"
    restart: always